/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lifeTutor;

import checker.SerChe;
import checker.Checker;
import generator.*;
import java.io.IOException;
import statistic.*;
import java.util.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *  Main class in program generates gui and allow user requested operations .
 * @author Dziki
 */
public class LifeTutor extends javax.swing.JFrame {
    
    Checker ch = new Checker();
    Generator gen = new Generator();
    String chat=new String();
    Stat stat=new Stat();

    /**
     * Creates new form NewJFrame
     */
    public LifeTutor() {
        initComponents();
    }
    
    void applyStat(){
        LGS.setText(stat.gS.toString());
        LWS.setText(stat.wS.toString());
        LGoodFiles.setText(stat.pFN.toString());
        LResAble.setText(stat.aTR.toString());
        LResNotAble.setText(stat.nATR.toString());
        LWInL.setText(stat.wIL.toString());
        LWrongFiles.setText(stat.wFN.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(32767, 5));
        TLibIn = new javax.swing.JTextField();
        TDicIn = new javax.swing.JTextField();
        BLibIncTxt = new javax.swing.JButton();
        BLibRd = new javax.swing.JButton();
        BLibSv = new javax.swing.JButton();
        BLibCl = new javax.swing.JButton();
        BDicIncTxt = new javax.swing.JButton();
        BDicRd = new javax.swing.JButton();
        BDicSv = new javax.swing.JButton();
        BDicCl = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TaChat = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        TfSend = new javax.swing.JTextField();
        BChatCl = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        TaMissSpelld = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        SpinNgDeg = new javax.swing.JSpinner();
        BChatSd = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        SpinWordsNum = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        LGS = new javax.swing.JLabel();
        LWS = new javax.swing.JLabel();
        LWInL = new javax.swing.JLabel();
        LResAble = new javax.swing.JLabel();
        LResNotAble = new javax.swing.JLabel();
        LWrongFiles = new javax.swing.JLabel();
        LGoodFiles = new javax.swing.JLabel();

        jScrollPane3.setViewportView(jTextPane3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(0, 0, 153));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));

        jLabel1.setBackground(new java.awt.Color(0, 0, 153));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Library name :");

        jLabel2.setBackground(new java.awt.Color(0, 0, 153));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Dictionary name :");

        TLibIn.setBackground(new java.awt.Color(0, 153, 255));
        TLibIn.setText("jTextField2");

        TDicIn.setBackground(new java.awt.Color(0, 153, 255));
        TDicIn.setText("jTextField3");

        BLibIncTxt.setBackground(new java.awt.Color(0, 102, 255));
        BLibIncTxt.setText("Include .txt to current");
        BLibIncTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BLibIncTxtActionPerformed(evt);
            }
        });

        BLibRd.setBackground(new java.awt.Color(0, 102, 255));
        BLibRd.setText("Read from .ser");
        BLibRd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BLibRdActionPerformed(evt);
            }
        });

        BLibSv.setBackground(new java.awt.Color(0, 102, 255));
        BLibSv.setText("Save as .ser");
        BLibSv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BLibSvActionPerformed(evt);
            }
        });

        BLibCl.setBackground(new java.awt.Color(0, 102, 255));
        BLibCl.setText("Clear current library");
        BLibCl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BLibClActionPerformed(evt);
            }
        });

        BDicIncTxt.setBackground(new java.awt.Color(0, 102, 255));
        BDicIncTxt.setText("Include .txt to current");
        BDicIncTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDicIncTxtActionPerformed(evt);
            }
        });

        BDicRd.setBackground(new java.awt.Color(0, 102, 255));
        BDicRd.setText("Read from .ser");
        BDicRd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDicRdActionPerformed(evt);
            }
        });

        BDicSv.setBackground(new java.awt.Color(0, 102, 255));
        BDicSv.setText("Save as .ser");
        BDicSv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDicSvActionPerformed(evt);
            }
        });

        BDicCl.setBackground(new java.awt.Color(0, 102, 255));
        BDicCl.setText("Clear current dictionary");
        BDicCl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDicClActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(BDicIncTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BDicRd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BDicSv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TDicIn))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TLibIn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BLibCl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BLibIncTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BLibRd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BLibSv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                .addComponent(BDicCl, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                .addGap(309, 309, 309))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TLibIn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BLibIncTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BLibRd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(BLibSv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BLibCl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TDicIn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BDicIncTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BDicRd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BDicSv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BDicCl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );

        jTabbedPane1.addTab("Customize library or dictionary", jPanel1);

        jPanel2.setBackground(new java.awt.Color(0, 0, 153));

        jLabel3.setBackground(new java.awt.Color(0, 0, 153));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Chat :");

        TaChat.setEditable(false);
        TaChat.setBackground(new java.awt.Color(0, 153, 255));
        TaChat.setColumns(20);
        TaChat.setRows(5);
        jScrollPane4.setViewportView(TaChat);

        jLabel4.setBackground(new java.awt.Color(0, 0, 153));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Write :");

        TfSend.setBackground(new java.awt.Color(0, 153, 255));
        TfSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfSendActionPerformed(evt);
            }
        });

        BChatCl.setBackground(new java.awt.Color(0, 102, 225));
        BChatCl.setText("Clear chat");
        BChatCl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BChatClActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(0, 0, 153));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Misspelled words:");

        TaMissSpelld.setEditable(false);
        TaMissSpelld.setBackground(new java.awt.Color(0, 153, 255));
        TaMissSpelld.setColumns(20);
        TaMissSpelld.setRows(5);
        jScrollPane5.setViewportView(TaMissSpelld);

        jLabel6.setBackground(new java.awt.Color(0, 0, 153));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Set n-gram deegre :");

        SpinNgDeg.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(2), Integer.valueOf(2), null, Integer.valueOf(1)));

        BChatSd.setBackground(new java.awt.Color(0, 102, 225));
        BChatSd.setText("Send");
        BChatSd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BChatSdActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(0, 0, 153));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Set respond size :");

        SpinWordsNum.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(5), Integer.valueOf(1), null, Integer.valueOf(1)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(255, 255, 255))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4)
                            .addComponent(TfSend)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(215, 215, 215)
                                .addComponent(BChatSd, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(87, 87, 87))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(SpinNgDeg)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(SpinWordsNum))
                                .addGap(67, 67, 67)))
                        .addContainerGap())))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(BChatCl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(366, 366, 366)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE))
                    .addComponent(jLabel4))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(TfSend))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(SpinNgDeg, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                        .addGap(3, 3, 3)
                        .addComponent(SpinWordsNum, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BChatCl, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                        .addComponent(BChatSd, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Chat", jPanel2);

        jPanel3.setBackground(new java.awt.Color(0, 0, 153));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel8.setBackground(new java.awt.Color(0, 0, 153));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Good Spelled :");

        jLabel9.setBackground(new java.awt.Color(0, 0, 153));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Wrong Spelled :");

        jLabel10.setBackground(new java.awt.Color(0, 0, 153));
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Words in Library :");

        jLabel11.setBackground(new java.awt.Color(0, 0, 153));
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Able to respond :");

        jLabel12.setBackground(new java.awt.Color(0, 0, 153));
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Not able to respond :");

        jLabel13.setBackground(new java.awt.Color(0, 0, 153));
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Wrong file names :");

        jLabel14.setBackground(new java.awt.Color(0, 0, 153));
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Proprer file names :");

        LGS.setBackground(new java.awt.Color(0, 153, 255));
        LGS.setForeground(new java.awt.Color(255, 255, 255));
        LGS.setText("0");

        LWS.setBackground(new java.awt.Color(0, 153, 255));
        LWS.setForeground(new java.awt.Color(255, 255, 255));
        LWS.setText("0");

        LWInL.setBackground(new java.awt.Color(0, 153, 255));
        LWInL.setForeground(new java.awt.Color(255, 255, 255));
        LWInL.setText("0");

        LResAble.setBackground(new java.awt.Color(0, 153, 255));
        LResAble.setForeground(new java.awt.Color(255, 255, 255));
        LResAble.setText("0");

        LResNotAble.setBackground(new java.awt.Color(0, 153, 255));
        LResNotAble.setForeground(new java.awt.Color(255, 255, 255));
        LResNotAble.setText("0");

        LWrongFiles.setBackground(new java.awt.Color(0, 153, 255));
        LWrongFiles.setForeground(new java.awt.Color(255, 255, 255));
        LWrongFiles.setText("0");

        LGoodFiles.setBackground(new java.awt.Color(0, 153, 255));
        LGoodFiles.setForeground(new java.awt.Color(255, 255, 255));
        LGoodFiles.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LResNotAble, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LWrongFiles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LGoodFiles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LGS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LWS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LWInL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LResAble, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(309, 309, 309))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LGS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LWS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LWInL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LResAble, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LResNotAble, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LWrongFiles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LGoodFiles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(110, 110, 110))
        );

        jTabbedPane1.addTab("Statistics", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BLibClActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BLibClActionPerformed
        gen.lib=new Library();
        TLibIn.setText("done");
        stat.wIL=gen.lib.next_key;
        applyStat();
    }//GEN-LAST:event_BLibClActionPerformed

    private void BLibIncTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BLibIncTxtActionPerformed
        try {
            gen.lib.read(TLibIn.getText());
        } catch (IOException ex) {
            TLibIn.setText("wrong file name");
            stat.wFN++;
            applyStat();
            return;
            
        }
        TLibIn.setText("done");
        stat.wIL=gen.lib.next_key;
        stat.pFN++;
        applyStat();
    }//GEN-LAST:event_BLibIncTxtActionPerformed

    private void BLibRdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BLibRdActionPerformed
        try {
            gen.lib =SerLib.deserialize(TLibIn.getText());
            
        } catch (IOException | ClassNotFoundException ex) {
            TLibIn.setText("wrong file name");
            stat.wFN++;
            applyStat();
            return;
        }
        TLibIn.setText("done");
        stat.wIL=gen.lib.next_key;
        stat.pFN++;
        applyStat();
    }//GEN-LAST:event_BLibRdActionPerformed

    private void BLibSvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BLibSvActionPerformed
        try {
            SerLib.serializeLib(gen.lib,TLibIn.getText());
        } catch (IOException ex) {
            TLibIn.setText("wrong file name");
            stat.wFN++;
            applyStat();
            return;
        }
        TLibIn.setText("done");
        stat.wIL=gen.lib.next_key;
        stat.pFN++;
        applyStat();
    }//GEN-LAST:event_BLibSvActionPerformed

    private void BDicIncTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDicIncTxtActionPerformed
        try {
            ch.read(TDicIn.getText());
        } catch (IOException ex) {
            TDicIn.setText("wrong file name");
            stat.wFN++;
            applyStat();
            return;
        }
        TDicIn.setText("done");
        stat.wIL=gen.lib.next_key;
        stat.pFN++;
        applyStat();
        
    }//GEN-LAST:event_BDicIncTxtActionPerformed

    private void BDicRdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDicRdActionPerformed
        try {
            SerChe.deserializeCheck(TDicIn.getText());
            
        } catch (IOException | ClassNotFoundException ex) {
            TDicIn.setText("wrong file name");
            stat.wFN++;
            applyStat();
            return;
        }
        TDicIn.setText("done");
        stat.wIL=gen.lib.next_key;
        stat.pFN++;
        applyStat();
    }//GEN-LAST:event_BDicRdActionPerformed

    private void BDicSvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDicSvActionPerformed
        try {
            SerChe.serializeCheck(ch,TDicIn.getText());
        } catch (IOException ex) {
            TDicIn.setText("wrong file name");
            stat.wFN++;
            applyStat();
            return;
        }
        TDicIn.setText("done");
        stat.wIL=gen.lib.next_key;
        stat.pFN++;
        applyStat();
    }//GEN-LAST:event_BDicSvActionPerformed

    private void BDicClActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDicClActionPerformed
        ch=new Checker();
        TDicIn.setText("done");
    }//GEN-LAST:event_BDicClActionPerformed

    private void TfSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfSendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfSendActionPerformed

    private void BChatSdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BChatSdActionPerformed
        String line;
        ArrayList<String>wrdarr=new ArrayList<>();
        line = TfSend.getText();
        Pattern pattern = Pattern.compile("\\w+");
            Matcher matcher = pattern.matcher(line);
            while (matcher.find()) {
                wrdarr.add(matcher.group());
            }
        
        
        TfSend.setText("");
        StringBuilder miss=new StringBuilder();
        miss.append("Miss spelled words will be skipped :").append("\n");
        ArrayList<String>words= new ArrayList<>();
        chat+="U: ";
        for(String b : wrdarr){
            if(ch.includes(b.toCharArray())){
                words.add(b);
                chat+=b+" ";
                stat.gS++;
            }
            else{
                miss.append(b).append("\n");
                stat.wS++;
            }
        }
        
        TaMissSpelld.setText("");
        TaMissSpelld.setText(miss.toString());
        
        chat+="\n";
        TaChat.setText(chat);
        
        Integer n=(Integer)SpinNgDeg.getValue();
        Integer wrdNum=(Integer)SpinWordsNum.getValue();
        
        if(n>words.size()){
            chat+="K: N-gram degree is bigger than question \n";
            stat.nATR++;
        }
        else{
            String generated=gen.generate(words,wrdNum);
            chat +=generated;
            if(generated.equals("K: n-gram deegre bigger than words number in library \n")||
                    generated.equals("K: no matches found \n")||
                    generated.equals("K: error unable to generate next word probably last generated word was last in library \n")
                    )stat.nATR++;
            else
                stat.aTR++;

        }
        TaChat.setText(chat);
        applyStat();
    }//GEN-LAST:event_BChatSdActionPerformed

    private void BChatClActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BChatClActionPerformed
        TaChat.setText("");
        chat="";
    }//GEN-LAST:event_BChatClActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LifeTutor().setVisible(true);
               
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BChatCl;
    private javax.swing.JButton BChatSd;
    private javax.swing.JButton BDicCl;
    private javax.swing.JButton BDicIncTxt;
    private javax.swing.JButton BDicRd;
    private javax.swing.JButton BDicSv;
    private javax.swing.JButton BLibCl;
    private javax.swing.JButton BLibIncTxt;
    private javax.swing.JButton BLibRd;
    private javax.swing.JButton BLibSv;
    private javax.swing.JLabel LGS;
    private javax.swing.JLabel LGoodFiles;
    private javax.swing.JLabel LResAble;
    private javax.swing.JLabel LResNotAble;
    private javax.swing.JLabel LWInL;
    private javax.swing.JLabel LWS;
    private javax.swing.JLabel LWrongFiles;
    private javax.swing.JSpinner SpinNgDeg;
    private javax.swing.JSpinner SpinWordsNum;
    private javax.swing.JTextField TDicIn;
    private javax.swing.JTextField TLibIn;
    private javax.swing.JTextArea TaChat;
    private javax.swing.JTextArea TaMissSpelld;
    private javax.swing.JTextField TfSend;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextPane jTextPane3;
    // End of variables declaration//GEN-END:variables
}
